# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json

modules:
  - type: dnf
    install:
      packages:
        - plocate
        - fcitx5
        - fcitx5-rime
        - librime-lua
    remove:
      packages:
        - ibus
        - firefox
        - firefox-langpacks
