# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json

modules:
  - type: dnf
    install:
      packages:
        - plocate
        - fcitx5
        - fcitx5-rime
        - librime-lua
        - podman-compose
        - chntpw
        - libayatana-indicator-gtk3
        - libayatana-ido-gtk3
        - libayatana-appindicator-gtk3
    remove:
      packages:
        - ibus
        - firefox # Use flatpak instead
        - firefox-langpacks
